### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by amannayak0007** [YanisSOTO/faceTracking#2]
Hello,

I'm getting error when i try to run this project on Xcode 8. 

Error : "Module file was created by an older version of the compiler; rebuild 'FaceTracker' and try again" 

kindly help me.  

Thanks,
AMAN JAIN

**Comment by YanisSOTO** [comment]
Hello, 

this is an old framework in swift 2. I can't update it cause i've no more access to it... I'm sorry.

**Comment by amannayak0007** [comment]
Ok. Can u suggest me any other framework?

**Comment by YanisSOTO** [comment]
No sorry but you can create you own face tracker with Core Image 
[https://developer.apple.com/reference/coreimage/cidetector](https://developer.apple.com/reference/coreimage/cidetector)
[http://www.appcoda.com/face-detection-core-image/](http://www.appcoda.com/face-detection-core-image/)

**Comment by ChildDivin** [comment]
Hello , above link is not working please give me proper solution .

**Comment by YanisSOTO** [comment]
@ChildDivin Hello, link are fixed retry it

**Comment by GowthamYadav2105** [comment]
@YanisSOTO  Hello, I am requesting. Can u please send me updated framework or examples as like this for gif images Please
